# Generated by Django 2.2 on 2018-12-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='msg',
            table='msg',
        ),
    ]
