# Generated by Django 2.1 on 2018-12-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20181222_1724'),
        ('message', '0002_auto_20181210_1522'),
    ]

    operations = [
    ]
