# Generated by Django 2.0.2 on 2018-12-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_msgs',
            name='file',
        ),
        migrations.RemoveField(
            model_name='chat_msgs',
            name='pic',
        ),
    ]
