"""
Django settings for MxOnline project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR,'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xu+s%(*pqt741l%zp9$&)^3&z@4lpu8ha+)hzp4y%=-t!2o$7g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTHENTICATION_BACKENDS = (
    'users.views.CustomBackend',
)

# Application definition

INSTALLED_APPS = [
    'channels',
    'chat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'crispy_forms',
    'captcha',
    'pure_pagination',
    'ad',
    'salebuy',
    'seekhelp',
    'lostfound',
    'news',
    'message',
    'rest_framework',
    'systermmsg',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MxOnline.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #添加图片处理器，为了在课程列表中前面加上MEDIA_URL
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'MxOnline.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

#



# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 发送邮箱

EMAIL_HOST = "smtp.qq.com"
EMAIL_PORT = 25
EMAIL_HOST_USER = "1184405959@qq.com"
EMAIL_HOST_PASSWORD = "dwjybikeqdawhhbc"
EMAIL_USE_TLS= True
EMAIL_FROM = "1184405959@qq.com"


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

AUTH_USER_MODEL = 'users.UserProfile'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)


# 设置上传文件的路径
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')   # 指定根目录

#静态文件
# STATICFILES_ROOT = os.path.join(BASE_DIR, 'static')

#设置channels
ASGI_APPLICATION = "MxOnline.routing.application"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'LOCATION': 'redis://realtimedb.uay4jn.clustercfg.use1.cache.amazonaws.com:6379/',

        'CONFIG': {
            "hosts": [('localhost', 6379)],
        },
    },
}

if os.environ.get("ENVIRONMENT_NAME") in ("PRODUCTION",):
    SECRET_KEY = os.environ["MXONLINE_SECRET_KEY"]
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
    MXONLINE_BOT = os.environ["MXONLINE_BOT_URL"]

    DEBUG = False

    ALLOWED_HOSTS = ['*']

    DATABASES = {
        'default': {
            'ENGINE': os.environ['MXONLINE_DB_ENGINE'],
            'NAME': os.environ["MXONLINE_DB_NAME"],
            'HOST': os.environ["MXONLINE_DB_HOST"],
            'PORT': os.environ["MXONLINE_DB_PORT"],
            'USER': os.environ["MXONLINE_DB_USER"],
            'PASSWORD': os.environ["MXONLINE_DB_PASSWORD"],
        }
    }
else:
    SECRET_KEY = 'xu+s%(*pqt741l%zp9$&)^3&z@4lpu8ha+)hzp4y%=-t!2o$7g'
    DEBUG = True
    ALLOWED_HOSTS = ['*']
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'help',  # 数据库名字
            'USER': 'root',  # 账号
            'PASSWORD': '1234567',  # 密码
            'HOST': '127.0.0.1',  # IP
            'PORT': '3306',  # 端口
            'OPTIONS': {
                'isolation_level': None,
                "init_command": "SET foreign_key_checks = 0;",
            }
        }
    }