# Generated by Django 2.0.2 on 2018-12-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systermmsg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systermmsg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
